### ISSUE TITLE
Adjust axis labeling on time series chart plots in V3

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#119]
**x-axis (time)**  remove year from tick labels, set tick width to be something like 6 hours, so labels will look like 

`MM-DD:HHZ`

**y-axis (scalar)** set tick interval to a constant, and force "0" to be a tick.  suggest something like:

```
n=10
dy=(max_of_y_extent-min_of_y_extent)/n
ticks = min_of_y_extent : dy : max_of_y_extent
```

E.g., 

```
min_of_y_extent=-2
max_of_y_extent=2
n=10;
dy=.4
ticks= [   -2.0   -1.6   -1.2   -0.8   -0.4      0.0    0.4    0.8    1.2    1.6    2.0]
```

<img width="601" alt="Screenshot 2024-07-17 at 3 05 07 PM" src="https://github.com/user-attachments/assets/761d8a1b-1ab8-46d2-98eb-8f5f6c71a5b4">

**Comment by BrianOBlanton** [comment]
can the limits of the y-axis be set to a default range?  at least for the current chart size, setting the limits to -2 ==>> 2.5 adds a 0 tick.

**Comment by PhillipsOwen** [comment]
i can do that. but note it may not find the "0" on some obs datasets.

eastport for example (the most northerm/eastern obs on the map).

**Comment by PhillipsOwen** [comment]
Latest implementation was satisfactory. closing.
