### ISSUE TITLE
color legend image missing in AWS version

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#122]
![Screenshot 2024-07-18 at 1 04 39 PM](https://github.com/user-attachments/assets/ae66dda6-7b28-4fc6-be15-f6fe03c97e62)

**Comment by PhillipsOwen** [comment]
i believe that Lisa mentioned that there has to be a configuration update on the AWS geo server to correct this.

**Comment by lstillwe** [comment]
Yes, Phil is correct. I had to install the new geoserver styles in the AWS geoserver. 
They are there now and this issue has been fixed.
