### ISSUE TITLE
map refreshing when switching tabs

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#125]
The UI seems to refresh to the latest data when switching between different browser tabs.  

Desired behavior:  Don't refresh unless the user wants to refresh.

Browser: Chrome
OS: Mac

UIs: AWS, DEV, not sure about PROD

**Comment by BrianOBlanton** [comment]
Same issue in Firefox

**Comment by PhillipsOwen** [comment]
thanks for checking that. i have added lisa to the issue.
