### ISSUE TITLE
move layer delete (trash can) to the layer panel

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#126]
![Screenshot 2024-07-24 at 10 06 26 AM](https://github.com/user-attachments/assets/2acb77d3-4a6b-43d9-96f1-d359084c5b07)

this will eliminate an unnecessary mouse event.

**Comment by lstillwe** [comment]
I think Phil is working on a whole new layout for the layers panel, so this will probably be included with that.
