### ISSUE TITLE
tweak to color bar

### ISSUE THREAD

**Issue by rluettich** [RENCI/APSViz-UI-V3#176]
Make the color increment 0.2 m rather than what currently appears to be 0.14 m.  Ultimately, it would be good to have this adjust with the color scale.

**Comment by PhillipsOwen** [comment]
Seems to be related to issue #150

**Comment by rluettich** [comment]
Ultimately, yes, if this becomes a user specified capability the default setting will be relatively unimportant.

**Comment by lstillwe** [comment]
This has been added in issue #155
