### ISSUE TITLE
An instance name seemingly not applied when a model selection query is submitted.

### ISSUE THREAD

**Issue by shinbunya** [RENCI/APSViz-UI-V3#193]
It appears that, when an ADCIRC Model selection query is submitted, the specified instance name is ignored or not properly applied. See the attached image. Among the two instances appearing in the red circle, one of them is ncsc123_gfs and the other is ncsc123_gfs_da. An expected behavior should be only the ncsc123_gfs_da appearing as specified in the instance name field. Also, it would be nice if the specified instance name also appears in the text circled by red. This way, a user can confirm that a desired instance is returned before clicking a check box.

![image](https://github.com/user-attachments/assets/61b0609b-0150-43c1-9e47-4231df547af2)

**Comment by PhillipsOwen** [comment]
this is a duplicate of #128

**Comment by shinbunya** [comment]
Closing due to duplication.

**Comment by shinbunya** [comment]
Closing...

**Comment by PhillipsOwen** [comment]
your concern is valid. i created this issue because i saw the same thing.

i recently lowered the font size in that are. let me see if i can fit the instance name in there now.
