### ISSUE TITLE
Side-by-side layer comparison - requirements/behavior questions.

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#196]
Please let this issue be one stop shopping to discus the side-by-side layer comparison requirements.

1. (addressed, no) Does comparing 2 layers imply 2 legends on the map?
2. (addressed, #274 ) Should the legend be shown only when comparing layers of the same type, or one on each pane?
3. (addressed, no) Should the left panel be defaulted to the current selected layer?
4. (addressed) Currently it is a manual hit of a "reset" button on the compare tray. should there a be a reset button elsewhere?
5. (addressed, nothing) What happens to the control panel? should it be disabled?
6. (addressed, no) Should hurricane tracks be shown when comparing layers?
7. Should we support sharing a compare view?
8. (addressed, nothing) How should observation points be handled? currently defaulted to state of topmost layer.
9. (addressed) what should the z-index opportunities for the pane frame be.
10. (addressed) Should there be a button on the control-panel to remove compare/restore normal view?

**Comment by PhillipsOwen** [comment]
5. Addressed
10. Addressed

**Comment by PhillipsOwen** [comment]
9, 10 addressed

**Comment by PhillipsOwen** [comment]
1, 2, 3, 5, 6, 8 addressed

**Comment by lstillwe** [comment]
#7 - NO!!!!
