### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#199]
should we be addressing these?

PS C:\Users\powen\PycharmProjects\APSVIZ\APSViz-UI-V3> npm outdated
Package                              Current         Wanted         Latest  Location                                    Depended by
@babel/core                           7.24.4         7.25.2         7.25.2  node_modules/@babel/core                    APSViz-UI-V3
@babel/eslint-parser                  7.24.1         7.25.1         7.25.1  node_modules/@babel/eslint-parser           APSViz-UI-V3
@babel/preset-env                     7.24.4         7.25.4         7.25.4  node_modules/@babel/preset-env              APSViz-UI-V3
@babel/preset-react                   7.24.1         7.24.7         7.24.7  node_modules/@babel/preset-react            APSViz-UI-V3
@emotion/react                       11.11.4        11.13.3        11.13.3  node_modules/@emotion/react                 APSViz-UI-V3
@emotion/styled                      11.11.5        11.13.0        11.13.0  node_modules/@emotion/styled                APSViz-UI-V3
@eslint/js                             9.1.1          9.9.1          9.9.1  node_modules/@eslint/js                     APSViz-UI-V3
@faker-js/faker                        8.4.1          8.4.1          9.0.0  node_modules/@faker-js/faker                APSViz-UI-V3
@fontsource/inter                     5.0.18         5.0.20         5.0.20  node_modules/@fontsource/inter              APSViz-UI-V3
@mui/icons-material                  5.15.15         5.16.7          6.0.2  node_modules/@mui/icons-material            APSViz-UI-V3
@mui/joy                       5.0.0-beta.36  5.0.0-beta.48  5.0.0-beta.48  node_modules/@mui/joy                       APSViz-UI-V3
@mui/material                        5.15.15         5.16.7          6.0.2  node_modules/@mui/material                  APSViz-UI-V3
@mui/x-date-pickers                    7.4.0         7.15.0         7.15.0  node_modules/@mui/x-date-pickers            APSViz-UI-V3
@tanstack/eslint-plugin-query         5.35.6         5.53.0         5.53.0  node_modules/@tanstack/eslint-plugin-query  APSViz-UI-V3
@tanstack/react-query                 5.36.1         5.54.1         5.54.1  node_modules/@tanstack/react-query          APSViz-UI-V3
@turf/bearing                          6.5.0          6.5.0          7.1.0  node_modules/@turf/bearing                  APSViz-UI-V3
@turf/circle                           6.5.0          6.5.0          7.1.0  node_modules/@turf/circle                   APSViz-UI-V3
@turf/destination                      6.5.0          6.5.0          7.1.0  node_modules/@turf/destination              APSViz-UI-V3
@turf/dissolve                         6.5.0          6.5.0          7.1.0  node_modules/@turf/dissolve                 APSViz-UI-V3
@turf/dissolve                         6.5.0          6.5.0          7.1.0  node_modules/@turf/dissolve                 APSViz-UI-V3
@turf/distance                         6.5.0          6.5.0          7.1.0  node_modules/@turf/distance                 APSViz-UI-V3
@turf/flatten                          6.5.0          6.5.0          7.1.0  node_modules/@turf/flatten                  APSViz-UI-V3
axios                                  1.7.4          1.7.7          1.7.7  node_modules/axios                          APSViz-UI-V3
core-js                               3.37.0         3.38.1         3.38.1  node_modules/core-js                        APSViz-UI-V3
css-loader                            6.11.0         6.11.0          7.1.2  node_modules/css-loader                     APSViz-UI-V3
dayjs                                1.11.11        1.11.13        1.11.13  node_modules/dayjs                          APSViz-UI-V3
eslint                                8.57.0         8.57.0          9.9.1  node_modules/eslint                         APSViz-UI-V3
eslint-plugin-react                   7.34.1         7.35.2         7.35.2  node_modules/eslint-plugin-react            APSViz-UI-V3
eslint-webpack-plugin                  4.1.0          4.2.0          4.2.0  node_modules/eslint-webpack-plugin          APSViz-UI-V3
globals                               15.1.0         15.9.0         15.9.0  node_modules/globals                        APSViz-UI-V3
mapbox-gl                              3.3.0          3.6.0          3.6.0  node_modules/mapbox-gl                      APSViz-UI-V3
mini-css-extract-plugin                2.9.0          2.9.1          2.9.1  node_modules/mini-css-extract-plugin        APSViz-UI-V3
postcss                               8.4.38         8.4.45         8.4.45  node_modules/postcss                        APSViz-UI-V3
postcss-preset-env                     9.5.9          9.6.0         10.0.2  node_modules/postcss-preset-env             APSViz-UI-V3
react-router-dom                      6.23.1         6.26.1         6.26.1  node_modules/react-router-dom               APSViz-UI-V3
recharts                              2.12.6         2.12.7         2.12.7  node_modules/recharts                       APSViz-UI-V3
webpack-dev-server                     5.0.4          5.1.0          5.1.0  node_modules/webpack-dev-server             APSViz-UI-V3
ws                                    8.17.1         8.18.0         8.18.0  node_modules/ws                             APSViz-UI-V3

**Comment by mbwatson** [comment]
```
 @babel/core                           ^7.24.0  →         ^7.25.2
 @babel/eslint-parser                 ^7.23.10  →         ^7.25.1
 @babel/preset-env                     ^7.24.0  →         ^7.25.4
 @babel/preset-react                   ^7.23.3  →         ^7.24.7
 @emotion/react                       ^11.11.4  →        ^11.13.3
 @emotion/styled                      ^11.11.5  →        ^11.13.0
 @eslint/js                             ^9.1.1  →         ^9.10.0
 @faker-js/faker                        ^8.4.1  →          ^9.0.0
 @fontsource/inter                     ^5.0.16  →         ^5.0.21
 @mui/icons-material                  ^5.15.15  →          ^6.1.0
 @mui/joy                       ^5.0.0-beta.36  →  ^5.0.0-beta.48
 @mui/material                        ^5.15.15  →          ^6.1.0
 @mui/x-date-pickers                    ^7.4.0  →         ^7.16.0
 @tanstack/eslint-plugin-query         ^5.35.6  →         ^5.53.0
 @tanstack/react-query                 ^5.36.0  →         ^5.55.4
 @turf/bearing                          ^6.5.0  →          ^7.1.0
 @turf/circle                           ^6.5.0  →          ^7.1.0
 @turf/destination                      ^6.5.0  →          ^7.1.0
 @turf/dissolve                         ^6.5.0  →          ^7.1.0
 @turf/distance                         ^6.5.0  →          ^7.1.0
 @turf/flatten                          ^6.5.0  →          ^7.1.0
 axios                                  ^1.7.4  →          ^1.7.7
 core-js                               ^3.36.0  →         ^3.38.1
 css-loader                            ^6.10.0  →          ^7.1.2
 d3                                     ^7.8.5  →          ^7.9.0
 dayjs                                ^1.11.11  →        ^1.11.13
 dotenv-webpack                         ^8.0.1  →          ^8.1.0
 eslint                                ^8.57.0  →         ^9.10.0
 eslint-plugin-react                   ^7.34.1  →         ^7.35.2
 eslint-webpack-plugin                  ^4.0.1  →          ^4.2.0
 globals                               ^15.1.0  →         ^15.9.0
 mapbox-gl                              ^3.1.2  →          ^3.6.0
 mini-css-extract-plugin                ^2.8.1  →          ^2.9.1
 postcss                               ^8.4.35  →         ^8.4.45
 postcss-preset-env                     ^9.4.0  →         ^10.0.3
 react                                 ^18.2.0  →         ^18.3.1
 react-dom                             ^18.2.0  →         ^18.3.1
 react-refresh                         ^0.14.0  →         ^0.14.2
 react-router-dom                      ^6.23.1  →         ^6.26.2
 recharts                              ^2.12.6  →         ^2.12.7
 webpack                               ^5.90.3  →         ^5.94.0
 webpack-dev-server                     ^5.0.2  →          ^5.1.0
 ws                                    ^8.17.1  →         ^8.18.0
```
