### ISSUE TITLE
tweak to tweak to color bar

### ISSUE THREAD

**Issue by rluettich** [RENCI/APSViz-UI-V3#200]
Thanks for revising the color bar scale, however instead of there being 10 intervals, it appears there are 9.  This makes the intervals very awkward, e.g., 0, 0.22, 0.45, 0.67 ...., 2.00 rather than 0, 0.2, 0.4, 0.6, ..... 2.0.  Could this be adjusted one more time to have an even 10 intervals?

**Comment by rluettich** [comment]
it looks like this change only made it to the apsviz-nopp.adcircprediction.org site and not the apsviz.adcircprediction.org site.

A related issue, the actual color scale on the nopp  and regular sites are different.  The nopp site has more green/yellow in the middle and looks very sickly, while the regular site has aquablue and therefore less green/yellow in the middle.  This is a much better color range.

**Comment by lstillwe** [comment]
Just for informational purposes the current default colormap specification for maxele looks like this:
 <sld:ColorMapEntry color="#0024E3" quantity="0.00" label="0.00 m"/> \
 <sld:ColorMapEntry color="#0075D9" quantity="0.33" label="0.33 m"/> \
<sld:ColorMapEntry color="#14A988" quantity="0.67" label="0.67 m"/> \
<sld:ColorMapEntry color="#1DF553" quantity="1.00" label="1.00 m"/> \
<sld:ColorMapEntry color="#6EFE1C" quantity="1.33" label="1.33 m"/> \
<sld:ColorMapEntry color="#E7FF04" quantity="1.67" label="1.67 m"/> \
<sld:ColorMapEntry color="#FFF200" quantity="2.00" label="2.00 m"/> \
<sld:ColorMapEntry color="#FFB300" quantity="2.33" label="2.33 m"/> \
<sld:ColorMapEntry color="#FF7000" quantity="2.67" label="2.67 m"/> \
<sld:ColorMapEntry color="#FF2E00" quantity="3.00" label="3.00 m"/> \

**Comment by lstillwe** [comment]
@rluettich DO you want the default range to be 0 to 2 rather than 0 to 3?

**Comment by rluettich** [comment]
2m is fine.  The issue is having this split up in 10 increments.

Thanks,
Rick

**Comment by BrianOBlanton** [comment]
Lisa, try this: 

<sld:ColorMap>
   <sld:ColorMapEntry color="#313695" quantity="0.00" label="0.00 m"/>
   <sld:ColorMapEntry color="#323C98" quantity="0.20" label="0.20 m"/>
   <sld:ColorMapEntry color="#4E80B9" quantity="0.40" label="0.40 m"/>
   <sld:ColorMapEntry color="#84BAD8" quantity="0.60" label="0.60 m"/>
   <sld:ColorMapEntry color="#C0E3EF" quantity="0.80" label="0.80 m"/>
   <sld:ColorMapEntry color="#EFF9DB" quantity="1.00" label="1.00 m"/>
   <sld:ColorMapEntry color="#FEECA2" quantity="1.20" label="1.20 m"/>
   <sld:ColorMapEntry color="#FDBD6F" quantity="1.40" label="1.40 m"/>
   <sld:ColorMapEntry color="#F57A49" quantity="1.60" label="1.60 m"/>
   <sld:ColorMapEntry color="#D93629" quantity="1.80" label="1.80 m"/>
   <sld:ColorMapEntry color="#A50026" quantity="2.00" label="2.00 m"/>
</sld:ColorMap>

**Comment by lstillwe** [comment]
This issue has been addressed and deployed
