### ISSUE TITLE
Expand raster colormap style selection functionality

### ISSUE THREAD

**Issue by lstillwe** [RENCI/APSViz-UI-V3#205]
Expand raster colormap style selection functionality to include features such as, choosing another type of colormap and setting the number of intervals. Also include selection for making colormap type - "intervals" or "ramp".

**Comment by BrianOBlanton** [comment]
I'd be happy to work on this with you, in terms of the functionality and needs.  although probably not very helpful in terms of actual implementation...

**Comment by lstillwe** [comment]
Great! Thank you.

**Comment by lstillwe** [comment]
@BrianOBlanton I have this pretty much working now. I can demo at the team meeting. I remember that you mentioned maybe cutting down on the color ramps available. Right now I have included the 3 that you gave me, and everything from brewer. 

They just get included in the code like this ...

colorRamps = {
      DefaultMaxWaterLevel: ['#313695', '#323C98', '#4E80B9', '#84BAD8', '#C0E3EF', '#EFF9DB', '#FEECA2', '#FDBD6F', '#F57A49', '#D93629', '#A50026'],
      DefaultMaxWindVelocity: ['#3E26A9', '#4433CD', '#4743E8', '#4755F6', '#4367FE', '#337AFD', '#2D8CF4', '#259CE8', '#1BAADF', '#04B6CE', '#12BEB9', '#2FC5A2', '#47CB86', '#71CD64', '#9FC941', '#C9C128', '#EBBB30', '#FFC13A', '#FBD42E', '#F5E824', '#FAFB14'],
      DefaultMaxSignificantWaveHeight: ['#30123B', '#3D3790', '#455ACD', '#467BF3', '#3E9BFF', '#28BBEC', '#18D7CC', '#21EBAC', '#46F884', '#78FF5A', '#A3FD3C', '#C4F133', '#E2DD37', '#F6C33A', '#FEA531', '#FC8021', '#F05B11', '#DE3D08', '#C42502', '#A31201', '#7A0402'],
      GeoStyler: ['#E7000E', '#F48E00', '#FFED00', '#00943D', '#272C82', '#611E82'],
      GreenRed: ['#00FF00', '#FF0000'],
      ...brewer}
      
So if there are any other special ones that you wish to add, please just let me know and I will.

![Screenshot 2024-10-01 at 9 47 31 AM](https://github.com/user-attachments/assets/1920123f-beb5-4a9a-bd29-79d07965a661)

**Comment by BrianOBlanton** [comment]
Holy crap!  this is incredible!
