### ISSUE TITLE
NHC hurricane track toggle switch not working

### ISSUE THREAD

**Issue by rluettich** [RENCI/APSViz-UI-V3#212]
on apsviz.adcircprediction.org, when looking at a synoptic run, the NHC hurricane track pops up by default.  

- The toggle switch in the legend block doesn't work to turn it off.  
- For synoptic runs, the default for the NHC track should be off (since the two don't necessarily correspond).  It is great if the switch is available to turn the track on if desired as a reference.

**Comment by lstillwe** [comment]
Clicking on hurricane toggle button causes console error: "Could not locate layer 4469-2024091006-gfsforecast-hurr"
in map-context.js, toggleHurricaneLayerVisibility()
The id passed to toggleHurricaneLayerVisibility() is wrong.

**Comment by rluettich** [comment]
Lisa,

Thanks for the work around.  I hadn’t noticed that was there.  Given that it is there, I’d be fine if you took it off the legend.

Thanks,
Rick

**Comment by lstillwe** [comment]
All good @rluettich I have a fix delivered for this issue. Probably will be deployed today or tomorrow.
