### ISSUE TITLE
Add "clear compare" button to the control panel

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#217]
although there are a few ways to come out of "compare layer" mode, it may be advantageous to put the button to revert to default mode clearly visible on the control panel.

**Comment by lstillwe** [comment]
I think the best solution here would be to either add a different panel to the control panel that would become active when in compare mode, or a completely different popup component.

**Comment by PhillipsOwen** [comment]
i think the consensus at the meeting was another dialog that appears when in compare mode. 

this dialog should contain the selected left/right layer details and a button to restore default mode.
