### ISSUE TITLE
Need instance name in "Selected Layers"

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#236]
In this example, the two instances differ in the usual metadata by ONLY the instance name; ncsc123_gfs vs. ncsc123_gfs_da in this case.  Also not clear if the instance name is correctly being set in the Control Panel when switching between the two in the mapping UI.

<img width="1505" alt="Screenshot 2024-09-14 at 7 58 01 AM" src="https://github.com/user-attachments/assets/68c0c523-12bb-4566-817b-ce76d3f74654">

**Comment by PhillipsOwen** [comment]
note: the information listed changes when looking at synoptic and/or tropical runs.

there are a number of places where the model run information is listed. should there be an effort here to standardize?
- the selected model run tray
- the compare layers tray and map surface popup.
- the model selection tray

finally, i am not seeing a disconnect between instance names and gird labels between the selected layers and control panel.

here is a "selected layer" tray example of when the instance name is added for both synoptic runs. is this acceptable?

![image](https://github.com/user-attachments/assets/a0fce61d-dcb9-4db8-ade9-b2913f11e9cf)

**Comment by PhillipsOwen** [comment]
i refactored the code that the various components use to gather model run details into a common function.
