### ISSUE TITLE
legend information consistent with side by side compare layers feature

### ISSUE THREAD

**Issue by rluettich** [RENCI/APSViz-UI-V3#255]
The layer comparison slider is a very nice addition to the apsviz website.  However, the legend information only captures what is in the right hand panel, even if the slider is moved all the way to the right so that the left hand panel covers the entire screen.  I suppose one would ultimately have 2 legends in this case, one in the lower right hand corner for the right panel and one in the lower left hand corner for the left panel?

**Comment by PhillipsOwen** [comment]
please refer to issue #196 , line item number 1. this is an outstanding question that i have had since i implemented this functionality.

**Comment by PhillipsOwen** [comment]
this is going to be addressed in issue #270
