### ISSUE TITLE
Timeseries extraction at model location (not an OBS station)

### ISSUE THREAD

**Issue by BrianOBlanton** [RENCI/APSViz-UI-V3#273]
Adding the flowchart to describe overall process

![model_ts_flow](https://github.com/user-attachments/assets/d0ef6a22-a093-4fe5-b42d-7c6b3a7fe612)

**Comment by PhillipsOwen** [comment]
Implementation questions:

What is the complete list of "Relevant metadata"?
Will the current observation stations still be on the UI surface and be select-able?
Is the old obs chart getting replaced with this functionality?
Does choosing a run from the past have any implications on the data/rendered chart?
Is this functionality only charting forecasts?

**Comment by BrianOBlanton** [comment]
1. the run.properties key/value pairs
2. yes
3. what does "old" mean?   Currently in use?  if so, then 
4. no, other than the underlying data retrieved and plotted
5. no, it is the same functionality we already have in the charting but without OBSERVATION data.

**Comment by lstillwe** [comment]
Also - what does timemark mean here? Do we just pull out the whole span of time from the NetDCF file for the wetted node selected?

**Comment by PhillipsOwen** [comment]
perhaps a TDS URL that returns the data at a point would help here.
