### ISSUE TITLE
run information in APSViz legend

### ISSUE THREAD

**Issue by rluettich** [RENCI/APSViz-UI-V3#277]
when we do NHC based runs we may do the official track or we may do perturbations to the track (e.g., move the track 50% of the way to the edge of the cone of uncertainty).  We need a way to indicate whether we are doing the official (ofcl) track or a perturbation in the legend.

**Comment by PhillipsOwen** [comment]
is there something in the run properties that we can use to determine if the run is a perturbation?

**Comment by BrianOBlanton** [comment]
forcing.ensemblename: veerLeft75

**Comment by BrianOBlanton** [comment]
For now, just put a line in the control panel (below the instance name) called "meteorology" and put the value of forcing.ensemblename next to it.

**Comment by PhillipsOwen** [comment]
this look ok?
![image](https://github.com/user-attachments/assets/e5ce1be0-16c8-45aa-9a81-0e9a25901ce2)

**Comment by BrianOBlanton** [comment]
yes!

**Comment by PhillipsOwen** [comment]
slight mod and showing the tropical and synoptic views.
![image](https://github.com/user-attachments/assets/a0d7ce70-4e43-4fb4-bb02-e6c78e01ab6f)
![image](https://github.com/user-attachments/assets/0429476c-4ec5-4baf-a77b-972d6cc2bb75)

**Comment by BrianOBlanton** [comment]
fire away.
