### ISSUE TITLE
Observation chart - X-Axis labeling

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#284]
from RL:

the station time series plots in apsviz appear to use a time interval of 29 hrs.  

is it possible to make them correspond to even days?

**Comment by BrianOBlanton** [comment]
@powen can you please try setting these properties for the xaxis in the time series chart? 

interval={23}
angle={-90}

the "23" should put a tick at every 6-hour time.

**Comment by BrianOBlanton** [comment]
Let's try this function for setting xtick positions. it's not great, but should work for now.

function get_xtick_interval(data){
  var T, dt, intv, i1h, fac
  //time resolution in minutes
  dt = Math.abs((new Date(data[0].time) - new Date(data[1].time))) / (1000 * 60);
  // data length in "days"
  T = (data.length-1) * dt/24/60
  T = Math.max(Math.ceil(Math.log2(T)),1)
  // number of times in 1 hr in min
  i1h = 60 / dt
  intv=i1h-1;   // default to daily
  if ( T <= 0.5) {  // all ticks
    intv= 0;
  }
  else if ( T <= 1) {  // 1 hourly ticks
    intv = i1h-1;
  }
  else if ( T <= 3) {  // 6-hourly ticks
    intv = i1h*6-1;
  }
  else if ( T <= 4) {  // 12-hourly ticks
    intv = i1h*12-1;
  }
  return intv;
}

**Comment by PhillipsOwen** [comment]
thanks i will pump it in and send you the result.
