### ISSUE TITLE
Missing raster portion with color ramp as intervals

### ISSUE THREAD

**Issue by mbwatson** [RENCI/APSViz-UI-V3#290]
these are screenshots taken back-to-back with only the color ramp type different--intervals first, then ramp. you'll see it looks like we're missing the portion with the max value.

![Screenshot 2024-10-09 at 19-11-11 RENCI APSViz UI_V3](https://github.com/user-attachments/assets/839a34e1-3afc-4542-b529-b3fc668d070a)
![Screenshot 2024-10-09 at 19-11-31 RENCI APSViz UI_V3](https://github.com/user-attachments/assets/c9d24c1a-0d76-4664-8418-8ce122a45810)

**Comment by lstillwe** [comment]
Hey @mbwatson - I think this a duplicate of issue #278. If so, please close this one. I am currently working this problem.
Thanks!

**Comment by mbwatson** [comment]
you're right -- thanks!
