### ISSUE TITLE
Add collaborator logos to page

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#309]
add a small banner to include collaborator logos for:

- RENCI/UNC, NCSU, UGA
- DHS CRC
- The Water Institute for the Gulf
- NC Dept of Transportation

this banner could be placed 

- directly under the control panel, 
- or perhaps as a peer to the left of the leaflet logo in a single row across the bottom of the page.

**Comment by BrianOBlanton** [comment]
CRC:
![image](https://github.com/user-attachments/assets/aa789d5c-40af-4a15-b816-0eaefa12eccb)
https://www.coastalresiliencecenter.org/

RENCI:
![image](https://github.com/user-attachments/assets/1e37f749-2d3e-40a9-8a0c-6d9064c5fc3a)
https://renci.org/research/earth-data-science-research/

TWI:
![image](https://github.com/user-attachments/assets/8e3188be-2e32-4834-9c4b-e5bc3561ef66)

http://thewaterinstitute.org

NCSU: 
![Screenshot 2024-10-24 at 12 52 16 PM](https://github.com/user-attachments/assets/a69ec17b-428a-48b5-9bab-2ba21c2850f7)
https://ccee.ncsu.edu/research/ewc/

UGA: 
![image](https://github.com/user-attachments/assets/dd3c95f6-c03c-4a72-9be1-4055d9a36afc)
https://engineering.uga.edu/team_member/matthew-v-bilskie/

**Comment by PhillipsOwen** [comment]
this is what i have implemented. im looking for comments or to go with it...

![image](https://github.com/user-attachments/assets/8ea87e68-4eb7-4d76-8485-d119c8817bff)

**Comment by BrianOBlanton** [comment]
I would say "go for now"...

**Comment by lstillwe** [comment]
Can we tighten up the spacing between those logos? Or am I being too picky??

**Comment by PhillipsOwen** [comment]
tightened
![image](https://github.com/user-attachments/assets/69c6705e-319d-4416-b55e-19eb220d8994)
