### ISSUE TITLE
Turning off observations when there are observations selected

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#56]
consider what should happen when the observations button is turned off and there were observations selected in the view..

**Comment by lstillwe** [comment]
@PhillipsOwen is this fixed?

**Comment by PhillipsOwen** [comment]
i presumed it was because something was merged. maybe not.

if we want to remove all obs dialogs there is a method defined in components/trays/remove/remove-observations.js

**Comment by lstillwe** [comment]
Let's keep this around for now
