### ISSUE TITLE
Layer tray - Moving a layer up/down has no effect.

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#86]
Like the title says. the layer ordering is not affected by moving the layer position in the  layer list.

**Comment by mbwatson** [comment]
is this still an issue?

**Comment by PhillipsOwen** [comment]
im not sure. the other layers move around ok.

but is the obs layer always forced to be on top?

**Comment by mbwatson** [comment]
that's right. the observation layers never render below the raster layers. i think that was intentional. is that still the preference?

**Comment by PhillipsOwen** [comment]
it must all be ok then. 

sorry for the false alarm, closing this issue.
