### ISSUE TITLE
Hurricane layer tray and control panel buttons not kept in sync.

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#90]
the view/hide layer buttons in the hurricane layer tray and control panel are not kept in sync.

steps to reproduce:

1. open the model select tray and hit the submit button (retrieves all hurricane layers).
2. select any hurricane.
3. open the hurricane layer tray.
4. note that the control panel and hurricane tray buttons are not kept in sync.

**Comment by lstillwe** [comment]
This will be considered as part of issue #54. Both can be closed when hurricane layer support is completed.

**Comment by lstillwe** [comment]
This was fixed in PR #111
