### ISSUE TITLE
Newly added observation layers not handled properly

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#92]
the state for storing observation data is not getting updated when new observation layers are selected/loaded.

steps to reproduce:

1. refresh the app in the browser to set the default state.
2. remove all default layers from the map.
3. add a synoptic layer (other than something on 2024-04-17).
4. select an observation point.

observation: although the layer is inserted properly in the layer tray, the observation data in state has not been updated.

in a review of the code it was also discovered that the data gathering in default-layers.js needs to be updated to use TanStack.

**Comment by lstillwe** [comment]
Can this issue be closed? - fixed in PR #100. Thanks!

**Comment by PhillipsOwen** [comment]
i believe it can! i tested this (successfully) doing your PR for this functionality yesterday.

Closing...
